# Tomcat
server:
  tomcat:
    # 配置tomcat的临时目录,jar当前目录
    basedir: ./onex-temp
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  servlet:
    session:
      cookie:
        http-only: true

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      enabled: true
  mvc:
    favicon:
      enabled: true
    # 404时,不跳error页面, 直接抛出异常
    throw-exception-if-no-handler-found: true
    # 默认路径匹配策略
    # springboot2.6.0开始请求路径的默认策略AntPathMatcher更改为PathPatternParser
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # freemarker
  freemarker:
    suffix: .html
    request-context-attribute: ctx
  web:
    resources:
      # 不为工程中的资源文件建立映射
      add-mappings: false
  # fix easypoi duplicated bean issue
  main:
    allow-bean-definition-overriding: true
    # 允许循环依赖,springboot2.6.0开始默认禁止循环依赖
    allow-circular-references: true
  # quartz 定时任务
  quartz:
    ## 任务存储方式
    job-store-type: jdbc
    ## 自动启动
    auto-startup: false
  # 任务处理
  task:
    execution:
      # 线程名前缀
      thread-name-prefix: onex-thread-
      pool:
        # 核心线程数,控制可以启动的异步任务量
        core-size: 32
        # 最大线程数
        max-size: 64
        # 队列大小
        queue-capacity: 1024
        # 现成最大空闲时间(s)
        keep-alive: 300s
  # 数据库
  datasource:
    dynamic:
      druid:
        # 设置timeout毫秒
        connect-timeout: 10000000
        socket-timeout: 10000000
        filters: stat
    druid:
      # 管理面板
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: admin
        login-password: OneX@2022
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# mybatis plus
# see {https://mybatis.plus/config/}
mybatis-plus:
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 字段策略
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      # 逻辑删除配置
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # 关闭mp3.0自带的banner
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

## onex
onex:
  # 应用父ID
  parent-artifact-id: @project.parent.artifactId@
  # 应用ID
  artifact-id: @project.artifactId@
  # 版本号
  version: @project.version@
  # maven编译时间
  build-time: @maven.build.timestamp@
  # 过滤器
  filter:
    enable: false
    # 自定义过滤器
    httpRequestReplaceFilter: true
    crosFilter: true
    shiroFilter: true
    xssFilter: false
  # Shiro
  shiro:
    enable: false
    # 类型jwt/uuid
    type: jwt
  # mybatis配置
  mybatisplus:
    enable: false
  # 定时任务
  job:
    enable: false
    # 任务名称前缀
    code-prefix:
  # swagger
  swagger:
    enable: false
  # WebMVC
  webmvc:
    enable: false
  # async
  async:
    enable: false
  # cache
  cache:
    enable: false
  # 自动填充
  auto-fill:
    enable: false
  # 异常处理
  exception-handler:
    enable: false
    # 控制是否在ExceptionHandler中输入详细错误
    detail-msg: false
  # 日志
  log:
    enable: false
    # 存储方式
    type: db
  # 数据查询过滤
  data-query-filter:
    enable: false
  # oss
  oss:
    # 文件请求路径
    file-request-path: /oss/**
    # 文件存储路径,以/结尾
    file-storage-path: ./onex-oss/
  # 授权配置
  auth:
    # 访问控制
    access-control:
      enable: false
      # 扫描包
      scan-package: com.nb6868.onex
    # token在header中的key
    token-header-key: auth-token
    # token在jwt中的key
    token-jwt-key: sub
    # 访问白名单,若有需要将file-request-path也加入
    white-list: /favicon.ico,/static/**,/webjars/**,/ws/**,/druid/**,/doc.html,/swagger-resources,/v3/api-docs/**,/v2/api-docs/**,/oss/**
    # 验证码有效期
    captcha-timeout: 900000
    # 验证码类型
    captcha-type: spec
    # 二维码有效期
    qrcode-timeout: 300000
